services:
  front-test:
    build:
      context: ../front-end
      dockerfile: Dockerfile
      args:
        - URLBACK=back-test:9428
        - CMDBUILD=build:prodnoproxy
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 15s
    depends_on:
      back:
        condition: service_healthy


  back-test:
    environment:
      - CMDRUN=start:e2e
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/database:/backend/database

    healthcheck:
      test: curl "http://localhost:9428/api/status" | grep "ok" || exit 1
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 15s

  e2e:
    build:
      context: ../front-end
      dockerfile: Dockerfile-e2e
      args:
        - URLFRONT=front-test
    volumes:
      - e2e:/usr/local/app/test-results

    depends_on:
      front-test:
        condition: service_healthy

volumes:
  e2e:
