services:
  front-test:
    build:
      context: ../front-end
      dockerfile: ../front-end/Dockerfile-test
    ports:
      - 8080:80
  back-test:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile-test
    ports:
      - 8000:9428
    volumes:
      - ./backend/database:/backend/database

  playwright:
    build:

    ports:
      -
