services:
  front:
    build:
      context: ../front-end
      dockerfile: Dockerfile
      args:
        - URLBACK=back:9428
        - CMDBUILD=build:prod
    healthcheck:
      test: curl "http://back:8000/api/status" | grep "ok" || exit 1
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 15s


  back:
    environment:
      - CMDRUN=start:e2e
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/database:/backend/database

  e2e:
    build:
      context: ../front-end
      dockerfile: Dockerfile-e2e
    volumes:
      - ./e2e:/usr/local/app/test-results
