services:
  front:
    build:
      context: ../front-end
      dockerfile: Dockerfile
      args:
        - URLBACK=memorysateurs.com\/back
        - CMDBUILD=build:prod
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 15s
    depends_on:
      back:
        condition: service_healthy


  back:
    environment:
      - CMDRUN=start
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/database:/backend/database

    healthcheck:
      test: curl "http://localhost:9428/api/status" | grep "ok" || exit 1
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 15s
    
  reverseproxy:
    build:
      context: ./
      dockerfile: Dockerfile-proxy
      args:
        - URLBACK=memorysateurs.com
    ports:
      - 80:80
    depends_on:
      - front
      - back